# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercenter', '0004_auto_20161007_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='owner',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (-1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
