# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0005_auto_20161016_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=300, verbose_name='头像'),
        ),
    ]
